### ISSUE TITLE
pom

### ISSUE THREAD

**Issue by DarcyLeeDuni** [mreutegg/laszip4j#18] opened 2020-08-13 01:57 UTC
how many plugin and dependency are can not download

**Comment by mreutegg** [comment] 2020-08-13 18:45
Recent builds with maven 3.6.3 and Java 11 worked for me. Please add more details if something does not work.

**Comment by DarcyLeeDuni** [comment] 2020-08-14 03:26
always appear can not resolve maven-release-plugin but already download success.

**Comment by mreutegg** [comment] 2021-02-04 18:29
Cannot reproduce. Closing this issue.

**Closed by mreutegg** 2021-02-04 18:29 UTC
